apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: test-gitops
  description: This is GitOps manifest for test   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: gitops
  owner: user:default/guest 
  lifecycle: experimental
  dependsOn:
    - component:test
